services:
  rabbitmq:
    image: rabbitmq:management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5

  database:
    image: postgres:alpine
    environment:
      POSTGRES_USER: disysuser
      POSTGRES_PASSWORD: disyspw
      POSTGRES_DB: energydb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U disysuser -d energydb" ]
      interval: 10s
      timeout: 5s
      retries: 5


