spring:
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: ${SPRING_RABBITMQ_PORT}
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

energy:
  raw-queue:    energy.messages
  update-queue: energy.update
  final-queue:  energy.percentage



server:
  port: 8090
