spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

energy:

  update-queue: energy.update
  final-queue:  energy.percentage



server:
  port: 8090
