spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

energy:
  raw-queue:    energy.messages
  update-queue: energy.update
  final-queue:  energy.percentage



server:
  port: 8090
