spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
  jpa:
      hibernate:
        ddl-auto: update
  application:
    name: user-service
  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

energy:
  queue: energy.input
  association: COMMUNITY
  type: USER

server:
  port: 8080
