spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

  application:
    name: energy-rest-api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

energy:
  input-queue:      energy.input
  update-queue:     energy.update
  percentage-queue: energy.percentage




server:
  port: 8080


