spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energydb
    username: disysuser
    password: disyspw
  jpa:
    hibernate:
      ddl-auto: update
  jackson:
    serialization:
      write-dates-as-timestamps: false
    property-naming-strategy: LOWER_CAMEL_CASE

  application:
    name: energy-rest-api

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

energy:
  input-queue:     energy.input
  update-queue:     energy.update
  percentage-queue: energy.percentage




server:
  port: 8080


