spring:
  application:
    name: energy-rest-api

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}

energy:
  input-queue: energy.input
  update-queue: energy.update

server:
  port: 8080
